# transfer_funds — FINANCIAL. Moves money from one of the caller's accounts to
# any account. Conservation: total balance is unchanged.
function handle_transfer_funds(st::AppState, user::String, input::Dict{String,String})
    from = get(input, "from_account", "")
    to = get(input, "to_account", "")
    amount = tryparse(Int, get(input, "amount_cents", ""))
    amount === nothing && return (422, Dict("error" => "amount_cents must be an integer"))
    amount > 0 || return (422, Dict("error" => "amount must be positive"))
    amount <= 25000 || return (422, Dict("error" => "amount exceeds per-transfer limit"))
    memo = strip(get(input, "memo", ""))
    length(memo) > 120 && return (422, Dict("error" => "memo too long"))
    haskey(st.accounts, from) || return (404, Dict("error" => "unknown source account"))
    haskey(st.accounts, to) || return (404, Dict("error" => "unknown destination account"))
    from == to && return (422, Dict("error" => "source and destination must differ"))
    st.accounts[from]["owner"] == user || return (403, Dict("error" => "not your account"))
    st.accounts[from]["balance_cents"] >= amount || return (422, Dict("error" => "insufficient funds"))
    t1 = apply_delta!(st, from, -amount, "transfer to $to: $memo")
    t2 = apply_delta!(st, to, amount, "transfer from $from: $memo")
    push!(st.audit, "$user transferred $amount from $from to $to")
    (201, Dict("debit" => t1, "credit" => t2, "from_balance_cents" => st.accounts[from]["balance_cents"]))
end
